MvcMovie57/MvcMovie57/Models/Movie57.cs
/*using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcMovie57.Models
{
    public class Movie_57
    {
    }
}*/
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace MvcMovie57.Models
{
    public class Movie57
    {
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Title57 { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate57 { get; set; }

        [Range(1, 100)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price57 { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        [Required]
        [StringLength(30)]
        public string Genre57 { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(5)]
        [Required]
        public string Rating57 { get; set; }
    }
}

MvcMovie57/MvcMovie57/Controllers/Movie57Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie57.Models;

namespace MvcMovie57.Controllers
{
    public class Movie57Controller : Controller
    {
        private readonly MvcMovie57Context _context;

        public Movie57Controller(MvcMovie57Context context)
        {
            _context = context;
        }
        /*
        // GET: Movie57
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movie57.ToListAsync());
        }*/

        /*
        //Example: https://localhost:44351/Movie57/Index/?searchString=Ghost
        public async Task<IActionResult> Index(string searchString)
        {
            var movies = from m in _context.Movie57
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title57.Contains(searchString));
            }

            return View(await movies.ToListAsync());
        }
        */
        /*
        //Example: https://localhost:44351/Movie57/Index/ghost
        public async Task<IActionResult> Index(string id)
        {
            var movies = from m in _context.Movie57
                         select m;

            if (!String.IsNullOrEmpty(id))
            {
                movies = movies.Where(s => s.Title57.Contains(id));
            }

            return View(await movies.ToListAsync());
        }
        */
        // GET: Movies
        public async Task<IActionResult> Index(string movieGenre57, string searchString57)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery57 = from m in _context.Movie57
                                            orderby m.Genre57
                                            select m.Genre57;

            var movies = from m in _context.Movie57
                         select m;

            if (!string.IsNullOrEmpty(searchString57))
            {
                movies = movies.Where(s => s.Title57.Contains(searchString57));
            }

            if (!string.IsNullOrEmpty(movieGenre57))
            {
                movies = movies.Where(x => x.Genre57 == movieGenre57);
            }

            var movieGenreVM = new MovieGenreViewModel57
            {
                Genres57 = new SelectList(await genreQuery57.Distinct().ToListAsync()),
                Movies57 = await movies.ToListAsync()
            };

            return View(movieGenreVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Movie57/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie57 = await _context.Movie57
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie57 == null)
            {
                return NotFound();
            }

            return View(movie57);
        }

        // GET: Movie57/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movie57/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title57,ReleaseDate57,Genre57,Price57,Rating57")] Movie57 movie57)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie57);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie57);
        }

        // GET: Movie57/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie57 = await _context.Movie57.FindAsync(id);
            if (movie57 == null)
            {
                return NotFound();
            }
            return View(movie57);
        }

        // POST: Movie57/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title57,ReleaseDate57,Genre57,Price57,Rating57")] Movie57 movie57)
        {
            if (id != movie57.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie57);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Movie57Exists(movie57.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie57);
        }

        // GET: Movie57/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie57 = await _context.Movie57
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie57 == null)
            {
                return NotFound();
            }

            return View(movie57);
        }

        // POST: Movie57/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie57 = await _context.Movie57.FindAsync(id);
            _context.Movie57.Remove(movie57);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Movie57Exists(int id)
        {
            return _context.Movie57.Any(e => e.Id == id);
        }
    }
}

MvcMovie57/MvcMovie57/Views/Movie57/Create.cshtml
@model MvcMovie57.Models.Movie57

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Movie57</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title57" class="control-label"></label>
                <input asp-for="Title57" class="form-control" />
                <span asp-validation-for="Title57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate57" class="control-label"></label>
                <input asp-for="ReleaseDate57" class="form-control" />
                <span asp-validation-for="ReleaseDate57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre57" class="control-label"></label>
                <input asp-for="Genre57" class="form-control" />
                <span asp-validation-for="Genre57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price57" class="control-label"></label>
                <input asp-for="Price57" class="form-control" />
                <span asp-validation-for="Price57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating57" class="control-label"></label>
                <input asp-for="Rating57" class="form-control" />
                <span asp-validation-for="Rating57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie57/MvcMovie57/Views/Movie57/Delete.cshtml
@model MvcMovie57.Models.Movie57

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie57</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title57)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate57)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre57)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price57)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcMovie57/MvcMovie57/Views/Movie57/Details.cshtml
@model MvcMovie57.Models.Movie57

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie57</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title57)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate57)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre57)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price57)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price57)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcMovie57/MvcMovie57/Views/Movie57/Edit.cshtml
@model MvcMovie57.Models.Movie57


@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<h4>Movie57</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title57" class="control-label"></label>
                <input asp-for="Title57" class="form-control" />
                <span asp-validation-for="Title57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate57" class="control-label"></label>
                <input asp-for="ReleaseDate57" class="form-control" />
                <span asp-validation-for="ReleaseDate57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre57" class="control-label"></label>
                <input asp-for="Genre57" class="form-control" />
                <span asp-validation-for="Genre57" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price57" class="control-label"></label>
                <input asp-for="Price57" class="form-control" />
                <span asp-validation-for="Price57" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Rating57" class="control-label"></label>
                <input asp-for="Rating57" class="form-control" />
                <span asp-validation-for="Rating57" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie57/MvcMovie57/Views/Movie57/Index.cshtml
@*@model IEnumerable<MvcMovie57.Models.Movie57>*@
@model MvcMovie57.Models.MovieGenreViewModel57
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Movie57" asp-action="Index" method="get">
    <p>
        <select asp-for="MovieGenre57" asp-items="Model.Genres57">
            <option value="">All</option>
        </select>
        Title: <input type="text" name="SearchString57">
        <input type="submit" value="Filter" />
    </p>
</form>

@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price57)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title57)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate57)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre57)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price57)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Movies57[0].Title57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movies57[0].ReleaseDate57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movies57[0].Genre57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movies57[0].Price57)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movies57[0].Rating57)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Movies57)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title57)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate57)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre57)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price57)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating57)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>