MVCUnitTestingDemo57/MVCUnitTestingDemo57/Models/Employee57.cs
/*using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCUnitTestingDemo57.Models
{
    public class Employee57
    {
    }
}*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCUnitTestingDemo57.Models
{
    public class Employee57
    {
        public int ID { get; set; }
        public string Name57 { get; set; }
        public DateTime JoiningDate57 { get; set; }
        public int Age57 { get; set; }
    }
}

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Controllers/Employee57Controller.cs
/*using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCUnitTestingDemo57.Controllers
{
    public class Employee57Controller : Controller
    {
        // GET: Employee57
        public ActionResult Index()
        {
            return View();
        }
    }
}*/

using MVCUnitTestingDemo57.Models;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web;
using System.Web.Mvc;

namespace MVCUnitTestingDemo57.Controllers
{
    public class Employee57Controller : Controller
    {
        [NonAction]

        public List<Employee57> GetEmployeeList()
        {
            return new List<Employee57>{
            new Employee57{
               ID = 1,
               Name57 = "Allan",
               JoiningDate57 = DateTime.Parse(DateTime.Today.ToString()),
               Age57 = 23
            },

            new Employee57{
               ID = 2,
               Name57 = "Carson",
               JoiningDate57 = DateTime.Parse(DateTime.Today.ToString()),
               Age57 = 45
            },

            new Employee57{
               ID = 3,
               Name57 = "Carson",
               JoiningDate57 = DateTime.Parse(DateTime.Today.ToString()),
               Age57 = 37
            },

            new Employee57{
               ID = 4,
               Name57 = "Laura",
               JoiningDate57 = DateTime.Parse(DateTime.Today.ToString()),
               Age57 = 26
            },
         };
        }

        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Employees()
        {
            var employees57 = from e57 in GetEmployeeList()
                            orderby e57.ID
                            select e57;
            return View(employees57);
        }
    }
}

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCUnitTestingDemo57.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Views/Employee57/Employees.cshtml
@model IEnumerable<MVCUnitTestingDemo57.Models.Employee57>

@{
    ViewBag.Title = "Employees";
}

<h2>Employees</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name57)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JoiningDate57)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age57)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name57)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JoiningDate57)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age57)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCUnitTestingDemo57/MVCUnitTestingDemo57/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Employees List", "Employees", "Employee57")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>